# Generated by Django 4.1.7 on 2023-03-14 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('string', models.CharField(max_length=200)),
                ('integer', models.IntegerField()),
                ('decimal', models.DecimalField(decimal_places=5, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'EXAMPLES',
            },
        ),
    ]
